### ISSUE TITLE
USER STORY: NAVBAR AVAILABILITY

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#1]
As a **user** I can **always view the Navbar regardless of which page I am on or where I am on that page** so that **I can navigate the site efficiently.**

**EPIC**

*   Epic Title: NAVBAR

**Tasks:**

- [x]   Build a Navbar component.
- [x]   Add links to other pages/routes.
- [x]   Place the navbar component in a position to not be affected by routing on the layout page.
- [x]   Fix the Navbar position to the top of the page.
- [x]   Build a Hamburger Menu

**Acceptance Criteria:**

- [x]   Navbar links route user to other pages.
- [x]   Navbar shows on each page.
- [x]   Navbar is fixed to the top of the page.
