### ISSUE TITLE
USER STORY: ADD/VIEW ARTICLE

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#10]
As a **user** I can **create articles** so that **I can share my knowledge with others on the site.**

**EPIC**

*   Epic Title: ARTICLES

**Tasks:**
- [x] Create a route for the article creation form.
- [x] Create a create form with an axios request to update the API.
- [x] Add errors for inaccurate completion.
- [x] Create a route for a detailed article page with an axios request to get specified article.
- [x] Create Article card component passing article props.
- [x] Present to card to the article page.
- [x] Redirect from for to article page on successful completion.
- [x] Split components into smaller components.
- [x] Add edit button to only show if user is article owner (functionality to be added later).
- [x] Add placeholder like, comment and follow elements.

**Acceptance Criteria:**
- [x] Unacceptable data entered into the form shows error message.
- [x] Successful form completion updates API.
- [x] Successful form completion redirects to appropriate article page.
- [x] Article presents on the page.
- [x] Update button only appears for owner of article.
