### ISSUE TITLE
USER STORY: VIEW ARTICLES

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#11]
As a **user** I can **view all articles on the home page** so that **I can browse for content that might interest me.**

**EPIC**

*   Epic Title: ARTICLES

**Tasks:**
- [x] Create a grid component which makes an axios request for all articles and maps them to the page using the card component in a responsive grid format.
- [x] Add grid to home page.
- [x] Build a skeleton to mirror cards layout when loading the page.
- [x] Provide a message if no results found.

**Acceptance Criteria:**
- [x] All recent articles presented on the screen in grid format (amount dependant on backend pagination)
- [x] Grid is responsive.
- [x] Error message presents for bad request.
- [x] Skeleton presents for loading.
