### ISSUE TITLE
USER STORY: LIKE POSTS

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#12]
As a **user** I can **like other people posts** so that **I can show my approval.**

**EPIC**

*   Epic Title: ARTICLES

**Tasks:**
- [x] Create a like article hook to like and unlike posts via an axios post/delete to the likes API.
- [x] Update and the like count and present to card.
- [x] Link hook to like buttons.
- [x] Build restrictions to like button:
> - owner-can’t like.
> - logged out user-can’t like.
> - logged in user can like.

- [x] Add popups to detail restrictions.
- [x] Style liked icon dependant on liked status by user.

**Acceptance Criteria:**
- [x] Liked button provides popup telling you, you can’t like if logged out.
- [x] Liked button provides popup telling you, you can’t like if article owner.
- [x] Liked button changes style if liked and increases count by 1.
- [x] Liked button changes style back if like removed and decreases count by 1.
