### ISSUE TITLE
USER STORY: FILTER ARTICLES

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#13]
As a **user** I can **filter articles** so that **I can find the ones that meet my desired criteria.**

**EPIC**

*   Epic Title: ARTICLES

**Tasks:**
- [x] Move the articles request to a hook and pass it a fill API URL with filter variables.
- [x] Create contexts to share the filter states across the site for
> - Search field
> - Order by
> - Language
> - Liked by user
- [x] Create filter field components and add to home page for
> - Search field (text)
> - Ordered by (dropdown)
> - Language (dropdown)
> - Liked by user (switch)
- [x] Set handle functions to fields to update the filter states to be used in the API search parameters.
- [x] Reset Filters between URLS.

**Acceptance Criteria:**
- [x] Search field restricts to articles with the text provided in the title or article owner name.
- [x] Ordered field orders articles by
> - Date posted.
> - Number of likes
> - Number of comments
- [x] Language field restricts articles to those of selected language.
- [x] Liked by user switch restricts articles to those liked by users.
- [x] Multiple filters can be applied at the same time.
- [x] When moving to another URL (e.g. feed) the filters reset.
