### ISSUE TITLE
USER STORY: EDIT ARTICLES

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#15]
As a **user** I can **edit my own articles** so that **I can update info or correct mistakes where required.**

**EPIC**

*   Epic Title: ARTICLES

**Tasks:**
- [x] Create a route for the article edit form.
- [x] Create an edit form with existing article data and an axios request to update the API.
- [x] Add errors for inaccurate completion.
- [x] Link to edit button on article card.
- [x] Redirect back to home on successful completion.

**Acceptance Criteria:**
- [x] Edit button direct to edit form.
- [x] Edit form pre-populates with article data.
- [x] Errors appear for inaccurate data entry.
- [x] Redirected back to home page on successful update.
