### ISSUE TITLE
USER STORY: DELETE ARTICLES

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#16]
As a **user** I can **delete my own articles** so that **I can remove articles I am no longer happy with.**

**EPIC**

*   Epic Title: ARTICLES

**Tasks:**
- [x] Create a delete function for an axios request to delete from the API.
- [x] Link to delete button on article card.
- [x] Set redirect based on current location:
> - If useParams finds id – go back.
> - If useParams finds no id – refresh.

**Acceptance Criteria:**
- [x] Delete button deleted article.
- [x] If on grid component delete refreshes.
- [x] If on detailed page delete redirects back a page.
