### ISSUE TITLE
USER STORY: CREATE COMMENTS

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#17]
As a **user** I can **create comments on an article** so that **I can share my thoughts on it.**

**EPIC**

*   Epic Title: COMMENTS

**Tasks:**
- [x] Create a create comment form component.
- [x] Add the component to the Article page.
- [x] Set to only show for logged in users.
- [x] Add error message for blank submission.
- [x] Increase comment count in article.
- [x] Submit form to API.

**Acceptance Criteria:**
- [x] Form shows error on blank submission.
- [x] Form updates API comments on successful submission.
- [x] Comment count increases on article.
