### ISSUE TITLE
USER STORY: VIEW COMMENTS

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#18]
As a **user** I can **view comments that have been added to an article** so that **I can see what other people have posted.**

**EPIC**

*   Epic Title: COMMENTS

**Tasks:**

- [x] Update useArticle hook to also obtain comments API data related to that article.
- [x] Create a comment component with the required comment info.
- [x] Map over API comments results and present comment components to the Article page.

**Acceptance Criteria:**

- [x] Comments are presenting to the page.
- [x] Comments are related to the appropriate article.
- [x] Newly added comments are updating to the top of the comments section.
