### ISSUE TITLE
USER STORY: DELETE COMMENTS

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#19]
As a **user** I can **delete my own comments** so that **I can remove information I no longer wish to share with the site audience.**

**EPIC**

*   Epic Title: COMMENTS

**Tasks:**
- [x] Add an update/delete icon to allow delete action (re-use existing component)
- [x] Create a delete function for an axios request to delete from the API.
- [x] Update article state to reflect reduction of comment count.
- [x] Update comments state to exclude deleted comment.

**Acceptance Criteria:**
- [x] Update/delete button only appears for comment owner.
- [x] Delete comment removes comment from API.
- [x] Delete comment removes comment for article page.
