### ISSUE TITLE
USER STORY: LIGHT DARK MODE

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#2]
As a **user** I can **switch the application between light and dark mode** so that **the aesthetics and readability better suit my needs**.

**EPIC**

*   Epic Title: NAVBAR

**Tasks:**

- [x]    Set a Chakra theme.
- [x]    Add a switch to the navbar to toggle the Chakra theme.

**Acceptance Criteria:**

- [x]    Toggle changes theme back and forth.
