### ISSUE TITLE
USER STORY: EDIT COMMENTS

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#20]
As a **user** I can **edit my own comments** so that **I can fix mistakes I made in my original posts.**

**EPIC**

*   Epic Title: COMMENTS

**Tasks:**

- [x] Create a comments edit component.
- [x] Create errors for unacceptable inputs.
- [x] Create state on article page to show edit form.
- [x] Create cancel button to set show edit state to false.
- [x] Create a function to update the comment API and update the comments state.

**Acceptance Criteria:**

- [x] Edit form shows on article page when edit button is selected.
- [x] Edit form disappears from article page when cancel selected.
- [x] Invalid entry’s to edit form show errors.
- [x] Successful submission of edit from updates API.
- [x] Successful submission of edit from updates comment on Article page.
