### ISSUE TITLE
USER STORY: VIEW PROFILES

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#21]
As a **user** I can **view a list of article author profiles** so that **I can see who is making contributions.**

**EPIC**

*   Epic Title: PROFILES

**Tasks:**

- [x] Create a sidebar component.
- [x] Request most followed profiles.
- [x] Map over into sidebar component.
- [x] Create a page for all profiles with infinite scroll.
- [x] Profiles link to profile pages.

**Acceptance Criteria:**

- [x] Can view profiles in the sidebar.
- [x] Can access the full profile search page via the link at the bottom of the sidebar.
- [x] Can navigate to the profile URL via the profile name.
- [x] Can view all profiles on the main profile list page.
- [x] Infinite scroll working.
