### ISSUE TITLE
USER STORY: FILTER PROFILES

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#22]
As a **user** I can **filter and order the list of profiles** so that **I can locate the ones most interesting to me.**

**EPIC**

*   Epic Title: PROFILES

**Tasks:**

- [x] Create search filter on top of sidebar.
- [x] Create Search filter on the top of profile list page.
- [x] Create order drop down on profile list page.
- [x] Create dropdown so restrict search by followed, following, language.

**Acceptance Criteria:**

- [x] Can filter profile name using the search bar in the sidebar.
- [x] Can filter profile name using the search bar on the profile list page.
- [x] Can order profiles on the profile list page by specified categories.
- [x] Can filter profiles on the profile list page by those currentUser is following.
