### ISSUE TITLE
USER STORY: FOLLOW PROFILES

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#23]
As a **user** I can **follow or unfollow profiles** so that **my feed page represents articles that interest me.**

**EPIC**

*   Epic Title: PROFILES

**Tasks:**

- [x] Create profile data context.
- [x] Create follow unfollow buttons on all profile components.
- [x] Create a hook that updates the profile data on the API and also reflects the updates in the profile state in the profile sidebar, list page and the profile page.
- [x] Create a context trigger to act as a dependency in the use article hooks to update the article requests when following statuses are updated.

**Acceptance Criteria:**

- [x] Follow/unfollow button updates API.
- [x] Follow/unfollow button updates states across sidebar, article list page and article page.
- [x] Follow/unfollow button triggers a new article API request.
- [x] Follow status is reflected on the article footer.
- [x] Feed page reflects the followed profile articles.
- [x] Followed filter switch toggles followed profiles.
