### ISSUE TITLE
USER STORY: EDIT PROFILE INFO

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#24]
As a **user** I can **edit my own profile data** so that **I can reflect new information.**

**EPIC**

*   Epic Title: PROFILES

**Tasks:**

- [x] Create edit profile page component.
- [x] Create a hook to update API profile data.
- [x] Update currentUser context state to reflect changes in profile image.

**Acceptance Criteria:**

- [x] Update edit button navigates to edit form.
- [x] Edit form prepopulates with existing profile data.
- [x] Edit submission successfully updates profile data.
- [x] Edit cancel takes back to previous page.
- [x] Current user avatar state is updated to reflect new profile image.
