### ISSUE TITLE
USER STORY: PASSWORD RESET

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#25]
As a **user** I can **update my login password** so that **I can improve security if required.**

**EPIC**

*   Epic Title: PROFILES

**Tasks:**

- [x] Create edit profile page component.
- [x] Create a hook to update API profile data.
- [x] Update currentUser context state to reflect changes in profile image.

**Acceptance Criteria:**

- [x] Update edit button navigates to edit form.
- [x] Edit form pre-populates with existing profile data.
- [x] Edit submission successfully updates profile data.
- [x] Edit cancel takes back to previous page.
- [x] Current user avatar state is updated to reflect new profile image.
