### ISSUE TITLE
USER STORY: VIEW LANGUAGES

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#26]
As a **user** I can **view all the languages a profile author is experienced in** so that **I can follow people who are most relevant to my interests.**

**EPIC**

*   Epic Title: LANGUAGES

**Tasks:**

- [x] Create language list component to add to the bottom of the Profile page.
- [x] Create language card to demo the information of each language.
- [x] Create a language hook to obtain the language info from the API.

**Acceptance Criteria:**

- [x] Language shows with icon.
- [x] Years of experience is calculated correctly and presented in the card.
- [x] Confidence Shows in a bar colour coded.
- [x] Languages appear in order of exp.
