### ISSUE TITLE
USER STORY: ADD LANGUAGES

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#27]
As a **user** I can **add languages that I am experienced in to my profile** so that **I can encourage others to follow me if they are interested in languages I know.**

**EPIC**

*   Epic Title: LANGUAGES

**Tasks:**

- [x] Create add button and have it toggle show add state.
- [x] Create Edit component that appears on toggle.
- [x] Create hook that posts the language data and updates the languages state and the profile language count.
- [x] Add error messages to inaccurate form entries.

**Acceptance Criteria:**

- [x] Language form appears/disappears on button.
- [x] Errors appear in inaccurate data submitted.
- [x] Successful submission adds new language with data provided.
- [x] Profile language count increase without refresh requirement.
