### ISSUE TITLE
USER STORY: DELETE LANGUAGES

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#29]
As a **user** I can **delete languages that have added to my profile** so that **I can remove info I am not happy with.**

**EPIC**

*   Epic Title: LANGUAGES

**Tasks:**

- [x] Create Language delete hook.
- [x] Update the state of the languages and the profile language count.

**Acceptance Criteria:**

- [x] On deletion the language is removed from the profile.
