### ISSUE TITLE
USER STORY: SHOW APPROPRIATE LINKS

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#3]
As a **user** I can **only view the links in the Navbar that I have access to** so that **I understand immediately what options are available to me**.

**EPIC**

*   Epic Title: NAVBAR

**Tasks:**

- [x]   Add conditional rendering to links based on if a user is logged in.

**Acceptance Criteria:**

- [x]   Prior to Login check only appropriate links show.
- [x]   Login to check only appropriate links show.
- [x]   Test links to ensure functionality remains.
