### ISSUE TITLE
USER STORY: VIEW RECOMMENDED ARTICLES

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#30]
As a **user** I can **view all the recommended articles other users have sent to me** so that **I can access them directly from my profile.**

**EPIC**

*   Epic Title: RECOMMENDED

**Tasks:**

- [x] Create recommended list component to add to the bottom of the Profile page.
- [x] Create recommended card to demo the information of each recommendation.
- [x] Obtain recommended data from objects embedded into the profile and present as cards.

**Acceptance Criteria:**

Title shows.

- [x] Links works.
- [x] Shows who recommended by.
- [x] Details how long ago was recommended.
- [x] Can’t receive duplicate recommendations.
