### ISSUE TITLE
USER STORY: REMOVE RECOMMENDATIONS

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#32]
As a **user** I can **remove recommendations from my profile** so that **I am left with only articles I am interested in.**

**EPIC**

*   Epic Title: RECOMMENDED

**Tasks:**
- [x] Create delete button on recommended card.
- [x] Delete generates a confirmation check.
- [x] Create hook to delete recommendation.
- [x] Add notification for successful/failed deletion of recommendations.

**Acceptance Criteria:**
- [x] Delete button opens confirmation.
- [x] Successful submission gets notification.
- [x] Failed submission gets notification.
- [x] On success no longer shows.
