### ISSUE TITLE
USER STORY: VIEW ARTICLE LINKS

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#33]
As a **user** I can **view all the links related to an article** so that **I can access them directly from the article.**

**EPIC**

*   Epic Title: LINKS

**Tasks:**
- [x] Create link card.
- [x] Add link hook to useArticle hook.
- [x] Obtain recommended data and list as cards at the bottom of the article page.
- [x] Truncate long URLs.

**Acceptance Criteria:**
- [x] Link title shows.
- [x] Link opens a new page to link destination.
- [x] Link truncates if long.
- [x] Description shows if exists.
