### ISSUE TITLE
USER STORY: BUILD ROUTES

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#4]
As a **user** I can **navigate to various page components without a page refresh** so that **I have a better user experience**.

**EPIC**

*   Epic Title: ROUTING

**Tasks:**

- [x]    Build routes with react-router-dom.
- [x]    Set up a Layout Page providing consistent layout.

**Acceptance Criteria:**

- [x]    Use links to check page components rendering.

**Comment by Joe-Collins-1986** [comment]
Changed Layout page to standard app page as using the CreateBrowserRouter caused an issue with not being able to wrap a Provider with the currentUser Context state around the customised router. Therefore BrowserRouter was used.
