### ISSUE TITLE
USER STORY: REGISTER

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#6]
As a **user** can **register an account** so that my **account details are stored, a profile is set up for me and I can login to the site**.

**EPIC**

*   Epic Title: AUTHENTICATION

**Tasks:**

- [x]   Build a registration form posting to the backend registration route.
- [x]   Redirect to login page.

**Acceptance Criteria:**

- [x]    After registration check that a user has been created in the database and is serialized appropriately into the API.
- [x]    After registration check that a profile has been created in the database and is serialized appropriately into the API.
- [x]   After registration user redirected to login page component.
