### ISSUE TITLE
USER STORY: LOGIN

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#7]
As a **user** I can **login to my registered account** so that **I can use the sites full functionality**.

**EPIC**

*   Epic Title: AUTHENTICATION

**Tasks:**

- [x]   Build a login form posting to the backend login route.
- [x]   Build a current user context file to store the state of the logged in user which can be shared and updated across components via a Provider.
- [x]   Wrap current user provider around all routes to grant access to current user and set current user.

**Acceptance Criteria:**

- [x]   Confirm login was successful based on conditional rendering.
- [x]   Check backend API link to confirm login.
