### ISSUE TITLE
USER STORY: LOGOUT

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-Front-End#8]
As a **user** I can **logout of my account** so that **I can keep my account safe from others accessing it in my absence**.

**EPIC**

*   Epic Title: AUTHENTICATION

**Tasks:**

- [x]    Link Navbar sign out to a handleSign out function.
- [x]    Use function to post to backend logout route.
- [x]    Set current user state to null.

**Acceptance Criteria:**

- [x]   Check only appropriate links are rendering.
- [x]   Check backend API link to confirm logout.
